TUGAS 1.3 PNN
=======

ASTRI CAHYANINGTYAS
---------------------

KELAS : IF-39-02

NIM : 1301154548

In [103]:
import math
import numpy as np
import pandas as pd
import plotly
import plotly.graph_objs as go
import matplotlib
import matplotlib.pyplot as plt
from numpy import linalg as la
from plotly.offline import *
from plotly.graph_objs import *
from plotly import __version__
init_notebook_mode(connected=True)

LOAD DATA
=====

In [104]:
def load_data(filename):
    data = pd.read_csv(filename, delimiter=',').as_matrix()
    x = data[:,1:4]
    return x

train = load_data('data_train_PNN_HIW.csv')
test = load_data('data_test_PNN_HIW.csv')

def gaussian_pdf1(x, sigma, w):
    return math.exp( -(np.sum((x - w)**2)) / (2 * sigma**2) )

def gaussian_pdf2(x, sigma, w, p):
    return 1/(((2*3.14)**(p/2))*(sigma**p))*math.exp( -(np.sum((x - w)**2)) / (2 * sigma**2) )

sigma = 0.1

PLOT DATA TRAIN
========

In [105]:
dataTrain = pd.read_csv('data_train_PNN_HIW.csv', delimiter = ",")
dataTest = pd.read_csv('data_test_PNN_HIW.csv', delimiter = ",")

kelas1 = dataTrain.loc[dataTrain['label'] == 0]
kelas2 = dataTrain.loc[dataTrain['label'] == 1]
kelas3 = dataTrain.loc[dataTrain['label'] == 2]

In [106]:
kelas1 = kelas1.reset_index(drop = True)
kelas2 = kelas2.reset_index(drop = True)
kelas3 = kelas3.reset_index(drop = True)

In [107]:
trace1 = go.Scatter3d(
    name = 'kelas 0',
    x=kelas1['att1'],
    y=kelas1['att2'],
    z=kelas1['att3'],
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 0, 0.14)',
            width=0.2
        ),
        opacity=0.9
    )
)

trace2 = go.Scatter3d(
    name = 'kelas 1',
    x=kelas2['att1'],
    y=kelas2['att2'],
    z=kelas2['att3'],
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 217, 0.14)',
            width=0.2
        ),
        opacity=0.9
    )
)

trace3 = go.Scatter3d(
    name = 'Kelas 2',
    x=kelas3['att1'],
    y=kelas3['att2'],
    z=kelas3['att3'],
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 217, 0.14)',
            width=0.2
        ),
        opacity=0.9
    )
)

data = [trace1, trace2, trace3]

this_layout = go.Layout(
    title = 'Data Train',
#     height = '800' ,
    scene = dict(
        xaxis = dict(
            title='Att 1'),
        yaxis = dict(
            title='Att 2'),
        zaxis = dict(
            title='Att 3'),),
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=25
    )
)

fig = go.Figure(data=data, layout=this_layout)
iplot(fig, filename='Data Train Scatter')

PATTERN LAYER
=======

In [108]:
def pattern_layer(x, data=train):
    return np.array([gaussian_pdf1(x, sigma, w) for w in data])

print(test[0])
print()
print(pattern_layer(test[0]))

[ 2.06734516  2.50901315  2.21950748]

[  0.00000000e+000   0.00000000e+000   0.00000000e+000   0.00000000e+000
   4.22317420e-036   7.03078074e-191   4.27965051e-027   0.00000000e+000
   0.00000000e+000   4.95585293e-072   4.10595278e-032   2.45915956e-176
   1.65612597e-058   1.32845026e-012   0.00000000e+000   0.00000000e+000
   0.00000000e+000   4.24474762e-036   0.00000000e+000   4.93410623e-036
   2.97355936e-215   1.44917439e-292   0.00000000e+000   6.14792065e-250
   0.00000000e+000   0.00000000e+000   0.00000000e+000   0.00000000e+000
   0.00000000e+000   5.37984041e-253   1.55404931e-023   0.00000000e+000
   4.69354694e-193   1.40886354e-012   7.52944338e-209   0.00000000e+000
   1.38798728e-011   9.76393426e-018   8.58431466e-069   4.51581717e-003
   1.21067548e-045   0.00000000e+000   1.91868348e-224   0.00000000e+000
   0.00000000e+000   6.11965454e-067   0.00000000e+000   0.00000000e+000
   3.52179256e-035   1.61832147e-006   2.11649189e-020   2.16696084e-031
   0.0000000

In [109]:
def load_label(filename):
    data = pd.read_csv(filename, delimiter=',').as_matrix()
    x = data[:,-1]
    return x

dlabel_train = load_label('data_train_PNN_HIW.csv')
dlabel_train

array([ 2.,  2.,  2.,  2.,  0.,  2.,  0.,  2.,  1.,  0.,  0.,  1.,  0.,
        0.,  2.,  2.,  2.,  0.,  2.,  0.,  1.,  1.,  2.,  1.,  1.,  2.,
        1.,  2.,  1.,  2.,  1.,  1.,  1.,  0.,  0.,  2.,  0.,  0.,  0.,
        0.,  0.,  1.,  1.,  2.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,
        2.,  2.,  2.,  1.,  2.,  0.,  0.,  1.,  1.,  0.,  2.,  0.,  2.,
        0.,  2.,  1.,  2.,  2.,  2.,  2.,  0.,  1.,  1.,  1.,  0.,  0.,
        1.,  2.,  0.,  1.,  1.,  2.,  0.,  2.,  0.,  1.,  2.,  2.,  2.,
        2.,  2.,  0.,  2.,  1.,  1.,  1.,  2.,  1.,  1.,  0.,  1.,  2.,
        0.,  1.,  0.,  1.,  0.,  2.,  1.,  0.,  1.,  1.,  2.,  2.,  1.,
        2.,  0.,  1.,  2.,  2.,  2.,  0.,  2.,  2.,  2.,  0.,  0.,  2.,
        1.,  1.,  1.,  2.,  1.,  2.,  1.,  0.,  1.,  1.,  2.,  1.,  0.,
        2.,  0.,  2.,  0.,  2.,  0.,  2.])

In [110]:
np.zeros((test.shape[0], len(np.unique(label))))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [111]:
for x in test:
    hasil_pattern = pattern_layer(x)
    print(hasil_pattern)

[  0.00000000e+000   0.00000000e+000   0.00000000e+000   0.00000000e+000
   4.22317420e-036   7.03078074e-191   4.27965051e-027   0.00000000e+000
   0.00000000e+000   4.95585293e-072   4.10595278e-032   2.45915956e-176
   1.65612597e-058   1.32845026e-012   0.00000000e+000   0.00000000e+000
   0.00000000e+000   4.24474762e-036   0.00000000e+000   4.93410623e-036
   2.97355936e-215   1.44917439e-292   0.00000000e+000   6.14792065e-250
   0.00000000e+000   0.00000000e+000   0.00000000e+000   0.00000000e+000
   0.00000000e+000   5.37984041e-253   1.55404931e-023   0.00000000e+000
   4.69354694e-193   1.40886354e-012   7.52944338e-209   0.00000000e+000
   1.38798728e-011   9.76393426e-018   8.58431466e-069   4.51581717e-003
   1.21067548e-045   0.00000000e+000   1.91868348e-224   0.00000000e+000
   0.00000000e+000   6.11965454e-067   0.00000000e+000   0.00000000e+000
   3.52179256e-035   1.61832147e-006   2.11649189e-020   2.16696084e-031
   0.00000000e+000   0.00000000e+000   0.00000000e+

[  0.00000000e+000   0.00000000e+000   0.00000000e+000   0.00000000e+000
   8.00851987e-046   1.12612342e-187   7.83783476e-049   0.00000000e+000
   0.00000000e+000   8.68094420e-083   1.18461811e-013   3.88634854e-134
   9.82651610e-223   2.26577467e-045   0.00000000e+000   0.00000000e+000
   0.00000000e+000   5.10495654e-158   0.00000000e+000   4.14685689e-070
   3.63857910e-130   5.57814685e-194   0.00000000e+000   7.27871845e-112
   5.03916449e-274   1.21947313e-216   0.00000000e+000   7.95745969e-259
   0.00000000e+000   4.75582959e-169   3.49643701e-165   1.44194283e-270
   1.23512226e-135   3.09135751e-113   0.00000000e+000   0.00000000e+000
   3.82714211e-126   6.80250642e-132   1.54139476e-194   6.27935302e-075
   1.32579429e-004   4.26410268e-266   2.26209909e-071   0.00000000e+000
   1.28847687e-234   1.30126056e-253   0.00000000e+000   3.09721764e-233
   3.53467519e-031   4.60657388e-062   4.94718183e-034   2.19168038e-008
   0.00000000e+000   1.08377474e-294   6.98809325e-

SUMMATION LAYER
========

In [112]:
def summation_layer(test, label):
    labels = np.unique(label)
    sum_ = np.zeros((test.shape[0], labels.shape[0]))
    for i, _ in enumerate(test):
        g_ = pattern_layer(_)
        for j in labels:
            sum_[i, int(j)] = np.sum(g_[label[:]==j])
    return sum_

_summation = summation_layer(test, dlabel_train)
_summation

array([[  1.12832441e-002,   1.55404931e-023,   8.05554710e-001],
       [  4.94409289e-007,   2.70344874e-029,   5.86103152e-033],
       [  2.34349205e-003,   5.66574100e-055,   2.57602187e-064],
       [  2.01696557e-006,   1.51306526e-002,   7.11973264e-050],
       [  8.49494501e-014,   7.06337275e-059,   1.07150529e-061],
       [  4.28969823e-003,   1.50106191e-035,   1.90250396e-031],
       [  1.68423958e-006,   9.88691944e-008,   2.66708313e-025],
       [  2.85067980e-003,   2.27182513e-007,   4.92693174e-039],
       [  1.52375395e-003,   5.76785386e-005,   2.66701010e-050],
       [  2.84607593e-003,   2.79030495e-033,   3.21433862e-015],
       [  8.60039221e-008,   4.30751332e-004,   7.26609239e-006],
       [  5.24611938e-017,   3.84541072e-001,   3.47142402e-010],
       [  3.69987838e-015,   3.92379448e-008,   2.30636331e-023],
       [  1.18018461e-008,   1.28622940e-002,   1.60464471e-019],
       [  2.00563750e-021,   1.21673192e-005,   1.70749838e-009],
       [  

OUTPUT LAYER
======

In [113]:
def output_layer(summation):
    return np.array([np.argmax(_) for _ in summation])

label  = np.array(output_layer(_summation))
label

array([2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0, 2, 2, 2,
       1, 0, 2, 2, 2, 2, 2], dtype=int64)

Prediksi.csv

In [114]:
def load_id(filename):
    did = pd.read_csv(filename, delimiter=',').as_matrix()
    x = did[:,0:1]
    return x

id = load_id('data_test_PNN_HIW.csv')

In [115]:
from pandas import DataFrame
test_id = id
test_label = label
result = DataFrame({ 'id' : test_id,
                    'label' : test_label})
result

Exception: Data must be 1-dimensional

In [ ]:
result.to_csv('prediksi.csv', index= False)